name: Build YABR

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-15-intel ]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Build Debug
        run: ./gradlew :app:assembleDebug

      - name: Build Release
        run: ./gradlew :app:assembleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: YABR-${{ matrix.os }}
          path: app/build/outputs/apk/
